FROM aelf/node:testnet-1.3.0

COPY appsettings.json appsettings.LocalTestNode.json /app/
COPY W1ptWN5n5mfdVvh3khTRm9KMJCAUdge9txNyVtyvZaYRYcqc1.json /root/.local/share/aelf/keys/
ENV ASPNETCORE_ENVIRONMENT=LocalTestNode