FROM aelf/node:testnet-1.3.0

COPY appsettings.json appsettings.LocalTestNode.json /app/
COPY 2cJGkUmdAJEBtXVxoPRgnN5PMDyF1TKRHA3q6Kk9fJXCtRzfiZ.json /root/.local/share/aelf/keys/
ENV ASPNETCORE_ENVIRONMENT=LocalTestNode